# This workflow will build a Java project with Maven and delpoy it to remote server

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build-deploy-run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build package with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

      - name: Stop AWS API on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: sudo systemctl stop myapp.service

      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "target/backeventplanner.jar"
          strip_components: 1
          target: "/home/ec2-user/app"

      - name: Start AWS API on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: sudo systemctl start myapp.service